### PR TITLE
Support for C++ enum class [20065]

### PR DESCRIPTION
**Pull request by richiware**
Depends on:

- eprosima/idl-parser#112

### CODE REVIEW

**Review by adriancampo — APPROVED** [review]
LGTM with green ci

**Comment by richiware** [comment]
CI passed on this [manual action](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/7057001055) ✅

**Comment by 1823258216** [comment]
When will fastddsgen support enum class?

Will it be supported in fastdds v2.14.x?

**Comment by JLBuenoLopez-eProsima** [comment]
> When will fastddsgen support enum class?
> 
> Will it be supported in fastdds v2.14.x?

@1823258216 

Support for enum class will be released in the upcoming Fast DDS v3. I am afraid that this change will not be backported into Fast DDS v2.

**Comment by JLBuenoLopez-eProsima** [comment]
@1823258216 

The current plan is to release Fast DDS v3 by the end of the second quarter.

**Pull request merged**
