### PR TITLE
[20335] Fix TypeObjectPair API

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
eProsima/Fast-DDS#4368 modifies TypeObjectPair API. This PR updates the TypeObjectSupport tests template accordingly.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
[Manual CI](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/7843626956)

**Comment by JLBuenoLopez-eProsima** [comment]
[Manual CI](https://github.com/eProsima/Fast-DDS-Gen/actions/runs/7915079542) after rebase

**Comment by JLBuenoLopez-eProsima** [comment]
I will ask for a manual CI once the corresponding PR in Fast DDS is merged

**Review by adriancampo — APPROVED** [review]
Perhaps implementing two accessor functions in TypeObjectPair to replace complete_type_object.complete() and minimal_type_object.minimal() would enhance readability. Otherwise, I believe it's good.

**Comment by JLBuenoLopez-eProsima** [comment]
> Perhaps implementing two accessor functions in TypeObjectPair to replace complete_type_object.complete() and minimal_type_object.minimal() would enhance readability. Otherwise, I believe it's good. Waiting for that CI

I do not agree. The type already provides the accessors that are being used. It would be like a wrapper, but this is not done for any other substructure within the TypeObject. So I am for keeping it as it is for consistency reasons. As for readability, it clarifies which substructure is being accessed too.

**Review by adriancampo — APPROVED** [review]
LGTM with manual CI

**Pull request merged**
