### PR TITLE
[14455] Support ROS2 compatible topic naming (#111)

### PR DESCRIPTION
**Pull request by RFRIEDM-Trimble**
This adds the prefixes to topic names such the topics can communicate with a ROS2 node; it will also show up in a command line call of `ros2 topic list`

### CODE REVIEW

**Comment by RFRIEDM-Trimble** [comment]
Hello,

Is there anything need to be done to get this merged? I can record a demo or add some additional documentation?

**Comment by MiguelCompany** [comment]
The proper way to achieve this would be to implement support for the `@topic` annotation, according to DDS XTypes 1.3 section 7.3.1.2.1.16

**Comment by Ryanf55** [comment]
I don't understand why this was closed. 

> The proper way to achieve this would be to implement support for the `@topic` annotation, according to DDS XTypes 1.3 section 7.3.1.2.1.16

Just a note - the ROS generated IDL does not use `@topic`; my proposed solution above would still work with those messages.
```
$ cat /opt/ros/humble/share/std_msgs/msg/String.idl
// generated from rosidl_adapter/resource/msg.idl.em
// with input from std_msgs/msg/String.msg
// generated code does not contain a copyright notice


module std_msgs {
  module msg {
    @verbatim (language="comment", text=
      "This was originally provided as an example message." "\n"
      "It is deprecated as of Foxy" "\n"
      "It is recommended to create your own semantically meaningful message." "\n"
      "However if you would like to continue using this please use the equivalent in example_msgs.")
    struct String {
      string data;
    };
  };
};

```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Ryanf55

Thanks for the contribution.

Firstly, The proposed changes are not considered to have enough importance to make it into Fast DDS-Gen. Ideally, Fast DDS-Gen should be a tool completely independent of how other users/communities use it. Consequently, the `typeros2` option is a non-ideal workaround introduced to facilitate users the communication between a ROS 2 native application and a Fast DDS one.

Secondly, the templates being modified in the PR are the ones corresponding to an example which is generated by the tool in order to test that the types are correctly generated and sent. It is not intended to be an application generator or that the code generated is used to communicate with any other application different from the one generated by the tool.

Nevertheless, you might be interested on the custom template feature introduced in Fast DDS-Gen v2.5.0. I have issued a PR clarifying the way to use this feature in:

* eProsima/Fast-DDS-docs#552

**Pull request closed without merging**
